"""
TODO: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""

n = int(400000)
l = [1, 2]
i = 2
while i:
    if (l[i - 1] + l[i - 2]) >= n:
        break
    else:
        l.append(l[i - 1] + l[i - 2])
        i += 1

print(max(l))
